### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by ianwalter** [silentdragonz/riboflavin#1]
Hey @silentdragonz, I was about to create this library a mere 6 hours after you and luckily found this before I started. There are some improvements that I would like to make but since it's so new I wanted to make sure we aren't duplicating work. Are you actively working on this right now? I was planning to fix some tests and add some more convenience functions around uploading files. May I submit pull request(s)? Thanks.

**Comment by silentdragonz** [comment]
Go right ahead. I haven't made any changes since uploading it. Getting busy
with the holidays so I'd welcome any help.

**Comment by ianwalter** [comment]
Cool.
